DROP TABLE IF EXISTS users;

CREATE TABLE nodejs.users (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(20) NOT NULL,
    age INT UNSIGNED NOT NULL,
    married TINYINT(1) NOT NULL,
    comment TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id),
    UNIQUE KEY name_UNIQUE (name ASC)
) COMMENT="사용자 정보" DEFAULT CHARSET=utf8 ENGINE=InnoDB;
